// Auto-generated by: npm run supabase:types
// Regenerate after schema changes: supabase gen types typescript --local > types/supabase.ts
// This file is a manual stub — replace with the generated output once Supabase project is linked.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string; email: string | null; phone: string | null
          full_name: string | null; avatar_url: string | null
          role: 'buyer' | 'seller' | 'admin' | 'super_admin'
          is_active: boolean; created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      seller_profiles: {
        Row: {
          id: string; user_id: string; business_name: string
          display_name: string; slug: string; description: string | null
          logo_url: string | null; gstin: string | null; pan: string | null
          business_type: string | null; business_address_id: string | null
          bank_account_number: string | null; bank_ifsc: string | null
          bank_account_name: string | null; bank_verified: boolean
          kyc_status: 'pending' | 'submitted' | 'approved' | 'rejected'
          kyc_rejection_reason: string | null; is_active: boolean
          is_vacation_mode: boolean; commission_rate: number
          total_rating: number; total_reviews: number; total_sales: number
          created_at: string; updated_at: string; deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['seller_profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['seller_profiles']['Insert']>
      }
      categories: {
        Row: {
          id: string; parent_id: string | null; name: string; slug: string
          description: string | null; image_url: string | null
          icon_name: string | null; sort_order: number; level: number
          path: string | null; is_active: boolean
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['categories']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['categories']['Insert']>
      }
      products: {
        Row: {
          id: string; seller_id: string; category_id: string
          title: string; slug: string; description: string | null
          specifications: Json; brand: string | null; tags: string[]
          status: 'draft' | 'pending_review' | 'active' | 'paused' | 'rejected'
          rejection_reason: string | null; base_price: number; mrp: number
          min_order_qty: number; max_order_qty: number | null
          is_cod_available: boolean; return_policy_days: number
          warranty_info: string | null; country_of_origin: string
          hsn_code: string | null; gst_rate: number; weight_grams: number | null
          length_cm: number | null; width_cm: number | null; height_cm: number | null
          total_sold: number; average_rating: number; review_count: number
          view_count: number; search_vector: unknown
          created_at: string; updated_at: string; deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at' | 'search_vector'>
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      product_variants: {
        Row: {
          id: string; product_id: string; sku: string; title: string
          options: Json; price: number; mrp: number
          is_active: boolean; sort_order: number
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['product_variants']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['product_variants']['Insert']>
      }
      product_images: {
        Row: {
          id: string; product_id: string; variant_id: string | null
          storage_path: string; url: string; alt_text: string | null
          sort_order: number; is_primary: boolean; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['product_images']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['product_images']['Insert']>
      }
      inventory: {
        Row: {
          id: string; variant_id: string; quantity: number
          reserved_quantity: number; low_stock_threshold: number
          track_inventory: boolean; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['inventory']['Row'], 'id' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['inventory']['Insert']>
      }
      orders: {
        Row: {
          id: string; order_number: string; buyer_id: string
          shipping_address_id: string
          status: 'pending_payment' | 'payment_failed' | 'placed' | 'confirmed' |
                  'partially_shipped' | 'shipped' | 'out_for_delivery' | 'delivered' |
                  'cancelled' | 'return_requested' | 'returned' | 'refunded'
          subtotal: number; shipping_total: number; discount_total: number
          tax_total: number; grand_total: number; coupon_id: string | null
          coupon_discount: number; payment_method: string | null
          payment_status: 'pending' | 'paid' | 'failed' | 'refunded' | 'partially_refunded'
          notes: string | null; ip_address: string | null; user_agent: string | null
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['orders']['Insert']>
      }
      order_items: {
        Row: {
          id: string; order_id: string; seller_id: string; product_id: string
          variant_id: string; product_title: string; variant_title: string
          product_image_url: string | null; sku: string; quantity: number
          unit_price: number; mrp: number; subtotal: number
          tax_rate: number; tax_amount: number; hsn_code: string | null
          commission_rate: number; commission_amount: number; seller_payout_amount: number
          item_status: 'pending' | 'confirmed' | 'shipped' | 'delivered' |
                       'cancelled' | 'return_requested' | 'returned' | 'refunded'
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>
      }
      payments: {
        Row: {
          id: string; order_id: string; razorpay_order_id: string
          razorpay_payment_id: string | null; razorpay_signature: string | null
          amount: number; currency: string; method: string | null
          status: 'created' | 'authorized' | 'captured' | 'failed' | 'refunded'
          gateway_response: Json; idempotency_key: string
          captured_at: string | null; created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['payments']['Insert']>
      }
      reviews: {
        Row: {
          id: string; product_id: string; order_item_id: string
          buyer_id: string; seller_id: string; rating: number
          title: string | null; body: string | null
          is_verified_purchase: boolean; is_approved: boolean
          moderated_at: string | null; moderated_by: string | null
          helpful_count: number; not_helpful_count: number
          images: string[]; created_at: string; updated_at: string; deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>
      }
      disputes: {
        Row: {
          id: string; order_item_id: string; buyer_id: string; seller_id: string
          reason: string; description: string; resolution_type: string | null
          status: 'open' | 'awaiting_seller' | 'awaiting_buyer' | 'admin_review' | 'resolved' | 'closed'
          evidence_urls: string[]; resolved_at: string | null; resolved_by: string | null
          resolution_notes: string | null; sla_deadline: string; final_deadline: string
          created_at: string; updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['disputes']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['disputes']['Insert']>
      }
      notifications: {
        Row: {
          id: string; user_id: string; type: string; title: string
          body: string; data: Json; is_read: boolean; read_at: string | null
          channel: 'in_app' | 'email' | 'sms' | 'whatsapp' | 'push'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
    }
    Functions: {
      generate_order_number:  { Args: Record<never, never>; Returns: string }
      calculate_order_total:  { Args: { p_order_id: string }; Returns: { subtotal: number; shipping_total: number; discount_total: number; tax_total: number; grand_total: number }[] }
      compute_seller_payout:  { Args: { p_seller_id: string; p_period_start: string; p_period_end: string }; Returns: { order_item_id: string; order_number: string; gross_amount: number; commission_rate: number; commission_amount: number; refund_deduction: number; net_amount: number; settled_at: string }[] }
      is_admin:               { Args: Record<never, never>; Returns: boolean }
      get_seller_profile_id:  { Args: Record<never, never>; Returns: string }
    }
  }
}

// Convenience row types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
